//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosTallas
    {
        public int ID { get; set; }
        public int IdArticulo { get; set; }
        public string Talla { get; set; }
        public Nullable<int> Posicion { get; set; }
        public Nullable<int> IdArticuloTallaDetalleCliente { get; set; }
        public double CantidadUnidadLogistica { get; set; }
    
        public virtual Articulos Articulos { get; set; }
    }
}
